name: BuildAndRelease
on: push

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run -e m5stack-atom -e m5stack-stamp
      - name: Rename release files
        run: mv .pio/build/m5stack-atom/firmware.bin .pio/build/m5stack-atom/firmware-m5stack-atom.bin
      - name: Rename release files
        run: mv .pio/build/m5stack-stamp/firmware.bin .pio/build/m5stack-stamp/firmware-m5stack-stamp.bin
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            .pio/build/m5stack-atom/firmware-m5stack-atom.bin
            .pio/build/m5stack-stamp/firmware-m5stack-stamp.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}